kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-config
data:
  ChickenCheck_ConnectionString: {{ include "helpers.connectionString" . }}
  ChickenCheck_PublicPath: "public"
  ChickenCheck_Authentication__ApiUsername: {{ .Values.apiUser }}
  ChickenCheck_Authentication__ApiPassword: {{ .Values.apiPassword }}
  ChickenCheck_Domain: {{ .Values.domain }}
  ChickenCheck_BasePath: {{ .Values.basePath }}
  ChickenCheck_DataProtection__Path: {{ .Values.dataProtectionPath }}
  ChickenCheck_DataProtection__Certificate: {{ .Values.dataProtectionCertificate }}
  ChickenCheck_DataProtection__CertificatePassword: {{ .Values.dataProtectionCertificatePassword }}
  ChickenCheck_RequestScheme: {{ .Values.requestScheme }}
