kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-config
data:
  ChickenCheck_ConnectionString: {{ include "helpers.connectionString" . }}
  ChickenCheck_PublicPath: "public"
  ChickenCheck_Authentication__Domain: {{ .Values.authentication.domain }}
  ChickenCheck_Authentication__ClientId: {{ .Values.authentication.clientId }}
  ChickenCheck_Authentication__AccessRole: {{ .Values.authentication.accessRole }}
  ChickenCheck_Domain: {{ .Values.domain }}
  ChickenCheck_DataProtection__Path: {{ .Values.dataProtectionPath }}
  ChickenCheck_DataProtection__Certificate: {{ .Values.dataProtectionCertificate }}
  ChickenCheck_DataProtection__CertificatePassword: {{ .Values.dataProtectionCertificatePassword }}
