apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  Auth0ClientSecret: {{ .Values.authentication.clientSecret | b64enc }}
  AzureStorageConnectionString: {{ .Values.azureStorageConnectionString | b64enc }}
